import Head from "next/head";
import { Header } from "@/components/Header";
import { Navbar } from "@/components/Navbar";
import { Pagination } from "@/components/Pagination";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto mt-8">
        <Navbar/>
        <div className="mt-6 mb-8 flex justify-end">
          <Pagination
            currentPage={1}
            totalPages={5}
            onPageChange={() => { return 1 }} 
          />
        </div>
      </main>
    </>
  );
}
