import Head from "next/head";
import { Header } from "@/components/Header";
import { Navbar } from "@/components/Navbar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto mt-8">
        <Navbar/>
      </main>
    </>
  );
}
